export const registerFormData = [
  {
    placeholder: "Enter full name here",
    name: "name",
    label: "Full Name",
    required: true,
    id: "name",
    type: "text",
    value: "",
    errorMessages: "",
  },
  {
    placeholder: "Enter your business email",
    name: "email",
    label: "Email",
    required: true,
    id: "email",
    type: "email",
    value: "",
    errorMessages: "Invalid email address",
  },
  {
    placeholder: "Enter password",
    name: "password",
    label: "Password",
    required: true,
    id: "password",
    type: "password",
    value: "",
    errorMessages: "Password must be 8 charactors",
  },
];
